//Major Categories

var majorCategory = new Array("Agriculture & Natural Resources", "Arts", "Biology & Life Science", "Business", "Communications & Journalism", "Computers & Mathematics", "Education", "Engineering", "Health", "Humanities & Liberal Arts", "Industrial Arts & Consumer Services", "Interdisciplinary", "Law & Public Policy", "NA", "Physical Sciences", "Psychology & Social Work", "Social Science");

//Majors
var a = new Array();
a[0] = "";
a[1] = "GENERAL AGRICULTURE|AGRICULTURE PRODUCTION AND MANAGEMENT|AGRICULTURAL ECONOMICS|ANIMAL SCIENCES|FOOD SCIENCE|PLANT SCIENCE AND AGRONOMY|SOIL SCIENCE|MISCELLANEOUS AGRICULTURE|FORESTRY|NATURAL RESOURCES MANAGEMENT";
a[2] = "FINE ARTS|DRAMA AND THEATER ARTS|MUSIC|VISUAL AND PERFORMING ARTS|COMMERCIAL ART AND GRAPHIC DESIGN|FILM VIDEO AND PHOTOGRAPHIC ARTS|STUDIO ARTS|MISCELLANEOUS FINE ARTS";
a[3] = "ENVIRONMENTAL SCIENCE|BIOLOGY|BIOCHEMICAL SCIENCES|BOTANY|MOLECULAR BIOLOGY|ECOLOGY|GENETICS|MICROBIOLOGY|PHARMACOLOGY|PHYSIOLOGY|ZOOLOGY|NEUROSCIENCE|MISCELLANEOUS BIOLOGY|COGNITIVE SCIENCE AND BIOPSYCHOLOGY";
a[4] = "GENERAL BUSINESS|ACCOUNTING|ACTUARIAL SCIENCE|BUSINESS MANAGEMENT AND ADMINISTRATION|OPERATIONS LOGISTICS AND E-COMMERCE|BUSINESS ECONOMICS|MARKETING AND MARKETING RESEARCH|FINANCE|HUMAN RESOURCES AND PERSONNEL MANAGEMENT|INTERNATIONAL BUSINESS|HOSPITALITY MANAGEMENT|MANAGEMENT INFORMATION SYSTEMS AND STATISTICS|MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION";
a[5] = "COMMUNICATIONS|JOURNALISM|MASS MEDIA|ADVERTISING AND PUBLIC RELATIONS";
a[6] = "COMMUNICATION TECHNOLOGIES|COMPUTER AND INFORMATION SYSTEMS|COMPUTER PROGRAMMING AND DATA PROCESSING|COMPUTER SCIENCE|INFORMATION SCIENCES|COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY|COMPUTER NETWORKING AND TELECOMMUNICATIONS|MATHEMATICS|APPLIED MATHEMATICS|STATISTICS AND DECISION SCIENCE|MATHEMATICS AND COMPUTER SCIENCE";
a[7] = "GENERAL EDUCATION|EDUCATIONAL ADMINISTRATION AND SUPERVISION|SCHOOL STUDENT COUNSELING|ELEMENTARY EDUCATION|MATHEMATICS TEACHER EDUCATION|PHYSICAL AND HEALTH EDUCATION TEACHING|EARLY CHILDHOOD EDUCATION|SCIENCE AND COMPUTER TEACHER EDUCATION|SECONDARY TEACHER EDUCATION|||SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION|TEACHER EDUCATION: MULTIPLE LEVELS|LANGUAGE AND DRAMA EDUCATION|ART AND MUSIC EDUCATION|MISCELLANEOUS EDUCATION|LIBRARY SCIENCE";
a[8] = "ARCHITECTURE|GENERAL ENGINEERING|AEROSPACE ENGINEERING|BIOLOGICAL ENGINEERING|ARCHITECTURAL ENGINEERING|BIOMEDICAL ENGINEERING|CHEMICAL ENGINEERING|CIVIL ENGINEERING|COMPUTER ENGINEERING|ELECTRICAL ENGINEERING|ENGINEERING MECHANICS PHYSICS AND SCIENCE|ENVIRONMENTAL ENGINEERING|GEOLOGICAL AND GEOPHYSICAL ENGINEERING|INDUSTRIAL AND MANUFACTURING ENGINEERING|MATERIALS ENGINEERING AND MATERIALS SCIENCE|MECHANICAL ENGINEERING|METALLURGICAL ENGINEERING|MINING AND MINERAL ENGINEERING|NAVAL ARCHITECTURE AND MARINE ENGINEERING|NUCLEAR ENGINEERING|PETROLEUM ENGINEERING|MISCELLANEOUS ENGINEERING|ENGINEERING TECHNOLOGIES|ENGINEERING AND INDUSTRIAL MANAGEMENT|ELECTRICAL ENGINEERING TECHNOLOGY|INDUSTRIAL PRODUCTION TECHNOLOGIES|MECHANICAL ENGINEERING RELATED TECHNOLOGIES|MISCELLANEOUS ENGINEERING TECHNOLOGIES|MATERIALS SCIENCE";
a[9] = "NUTRITION SCIENCES|GENERAL MEDICAL AND HEALTH SERVICES|COMMUNICATION DISORDERS SCIENCES AND SERVICES|HEALTH AND MEDICAL ADMINISTRATIVE SERVICES|MEDICAL ASSISTING SERVICES|MEDICAL TECHNOLOGIES TECHNICIANS|HEALTH AND MEDICAL PREPARATORY PROGRAMS|NURSING|PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION|TREATMENT THERAPY PROFESSIONS|COMMUNITY AND PUBLIC HEALTH|MISCELLANEOUS HEALTH MEDICAL PROFESSIONS";
a[10] = "AREA ETHNIC AND CIVILIZATION STUDIES|LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE|FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES|OTHER FOREIGN LANGUAGES|ENGLISH LANGUAGE AND LITERATURE|COMPOSITION AND RHETORIC|LIBERAL ARTS|HUMANITIES|INTERCULTURAL AND INTERNATIONAL STUDIES|PHILOSOPHY AND RELIGIOUS STUDIES|THEOLOGY AND RELIGIOUS VOCATIONS|ANTHROPOLOGY AND ARCHEOLOGY|ART HISTORY AND CRITICISM|HISTORY|UNITED STATES HISTORY";
a[11] = "COSMETOLOGY SERVICES AND CULINARY ARTS|FAMILY AND CONSUMER SCIENCES|MILITARY TECHNOLOGIES|PHYSICAL FITNESS PARKS RECREATION AND LEISURE|CONSTRUCTION SERVICES|ELECTRICAL, MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION|TRANSPORTATION SCIENCES AND TECHNOLOGIES";
a[12] = "MULTI/INTERDISCIPLINARY STUDIES";
a[13] = "COURT REPORTING|PRE-LAW AND LEGAL STUDIES|CRIMINAL JUSTICE AND FIRE PROTECTION|PUBLIC ADMINISTRATION|PUBLIC POLICY";
a[14] = "N/A (less than bachelor's degree)";
a[15] = "PHYSICAL SCIENCES|ASTRONOMY AND ASTROPHYSICS|ATMOSPHERIC SCIENCES AND METEOROLOGY|CHEMISTRY|GEOLOGY AND EARTH SCIENCE|GEOSCIENCES|OCEANOGRAPHY|PHYSICS|MULTI-DISCIPLINARY OR GENERAL SCIENCE|NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL TECHNOLOGIES";
a[16] = "PSYCHOLOGY|EDUCATIONAL PSYCHOLOGY|CLINICAL PSYCHOLOGY|COUNSELING PSYCHOLOGY|INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY|SOCIAL PSYCHOLOGY|MISCELLANEOUS PSYCHOLOGY|HUMAN SERVICES AND COMMUNITY ORGANIZATION|SOCIAL WORK";
a[17] = "INTERDISCIPLINARY SOCIAL SCIENCES|GENERAL SOCIAL SCIENCES|ECONOMICS|CRIMINOLOGY|GEOGRAPHY|INTERNATIONAL RELATIONS|POLITICAL SCIENCE AND GOVERNMENT|SOCIOLOGY|MISCELLANEOUS SOCIAL SCIENCES";

function populateMajors(categoryElementId, majorElementId) {
    var selectedCategoryIndex = document.getElementById(categoryElementId).selectedIndex;

    var major = document.getElementById(majorElementId);

    major.length = 0;
    major.options[0] = new Option('Select Major', '');
    major.selectedIndex = 0;

    var major_arr = a[selectedCategoryIndex].split("|");

    for (var i =0; i< major_arr.length; i++){
        major.options[major.length] = new Option(major_arr[i], major_arr[i]);
    }
    
}

function populateCategories(categoryElementId, majorElementId) {
    var categoryElement = document.getElementById(categoryElementId);
    categoryElement.length = 0;
    categoryElement.options[0] = new Option('Select Category', '-1');
    categoryElement.selectedIndex = 0;

    for (var i=0; i< majorCategory.length; i++){
        categoryElement.options[categoryElement.length] = new Option(majorCategory[i], majorCategory[i]);

    }

    if(majorElementId){
        categoryElement.onchange = function () {
            populateMajors( categoryElementId, majorElementId );
        };
    }
}